"""Groq-based detection signal for Provenance Guard (Milestone 3).

This module wraps the Groq chat completions API and exposes a single
responsibility: given a block of text, return whether it looks more like
human or AI writing, along with a confidence score.
"""

from __future__ import annotations

import json
import os
from typing import TypedDict

from dotenv import load_dotenv
from groq import Groq

# Load environment variables from a local .env file (if present).
load_dotenv()

# Model used for the first detection signal.
GROQ_MODEL: str = "llama-3.3-70b-versatile"

# Instruction prompt sent to the model. It is intentionally strict about the
# output format so the response can be parsed as JSON.
DETECTION_PROMPT: str = (
    "Determine whether the following writing appears more likely to be "
    "written by a human or generated by AI.\n\n"
    "Respond ONLY using JSON in this format:\n\n"
    '{\n  "prediction":"Human",\n  "confidence":0.91\n}\n\n'
    "or\n\n"
    '{\n  "prediction":"AI",\n  "confidence":0.87\n}\n\n'
    "Do not include explanations."
)


class DetectionResult(TypedDict):
    """Shape of the value returned by :func:`detect`."""

    prediction: str
    confidence: float


class GroqDetectionError(RuntimeError):
    """Raised when the Groq detection signal cannot be produced."""


def _get_client() -> Groq:
    """Build a Groq client using the API key from the environment.

    Raises:
        GroqDetectionError: If the ``GROQ_API_KEY`` variable is missing.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise GroqDetectionError("GROQ_API_KEY is not configured.")
    return Groq(api_key=api_key)


def detect(text: str) -> DetectionResult:
    """Classify ``text`` as human- or AI-written using Groq.

    Args:
        text: The submitted content to analyze.

    Returns:
        A dictionary with ``prediction`` ("Human" or "AI") and a numeric
        ``confidence`` between 0 and 1.

    Raises:
        GroqDetectionError: If the API call fails or the response cannot be
            parsed into the expected structure.
    """
    client = _get_client()

    try:
        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": DETECTION_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
            response_format={"type": "json_object"},
        )
    except Exception as exc:  # noqa: BLE001 - surface any SDK/network error.
        raise GroqDetectionError("Groq API request failed.") from exc

    raw = completion.choices[0].message.content or ""

    try:
        parsed = json.loads(raw)
        prediction = str(parsed["prediction"])
        confidence = float(parsed["confidence"])
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        raise GroqDetectionError("Groq returned an unparseable response.") from exc

    return {"prediction": prediction, "confidence": confidence}
